/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javalinkedlist;
import java.io.*;
import java.util.*;
import javax.swing.JOptionPane;
/**
 *
 * @author Felipe & MatheusFranco
 */
public class FormSystem extends javax.swing.JFrame 
{
    LinkedList<Food> list = new LinkedList<>();
    Comparator<Food> compareEnergeticValue = (Food f1, Food f2) -> f1.getEnergeticValue() - f2.getEnergeticValue();
    Comparator<Food> compareNutrition = (Food f1, Food f2) -> f1.getNutrition() - f2.getNutrition();
    Comparator<Food> compareFat = (Food f1, Food f2) -> f1.getFat() - f2.getFat();
    
    public FormSystem() 
    {
        initComponents();
        loadArc();
    }

    private void loadArc()
    {
     String txtFile = "data.txt";
        String line = "";
        String[] read = null;
        try (BufferedReader br = new BufferedReader(new FileReader(txtFile))) {
            while ((line = br.readLine()) != null) {
                Food f = new Food();
                read = line.split(",");
                System.out.println("Name:"+read[0]+ " EnergV= " + read[1] + " , Nutrition=" + read[2] + "" + " , Fat=" + read[3]);
                f.setName(read[0]);
                f.setEnergeticValue(Integer.parseInt(read[1]));
                int nutrition = (Integer.parseInt(read[2]));
                f.setNutrition(nutrition);
                int fat = (Integer.parseInt(read[3]));
                f.setFat(fat);
                list.add(f); 
            }// fim percurso no arquivo
            showList();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
    
    void showList()
    {
        listFood.setText("");
        if(!list.isEmpty())
        {
            for(Food f:list)
            {
                listFood.append(f+"\n");
            }
        }
            
    }
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        txtName = new javax.swing.JTextField();
        txtEnergeticValue = new javax.swing.JTextField();
        txtNutrition = new javax.swing.JTextField();
        txtFat = new javax.swing.JTextField();
        txtPositionAdd = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btnSearchContains = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listFood = new javax.swing.JTextArea();
        btnResolver = new javax.swing.JButton();
        txtPosicaoRemove = new javax.swing.JTextField();
        btnOrdNutrition = new javax.swing.JButton();
        btnOrdEnergeticValue = new javax.swing.JButton();
        btnOrdName = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblProx = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 153, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Adicionar Alimento", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 24))); // NOI18N
        jPanel2.setToolTipText("Adicionar Alimento");
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtName.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        txtName.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nome", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Light", 0, 18))); // NOI18N
        jPanel2.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 262, -1));

        txtEnergeticValue.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        txtEnergeticValue.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Valor Energético", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Light", 0, 18))); // NOI18N
        jPanel2.add(txtEnergeticValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 190, -1));

        txtNutrition.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        txtNutrition.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nutrição (0 - 100)", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Light", 0, 18))); // NOI18N
        jPanel2.add(txtNutrition, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 150, -1));

        txtFat.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        txtFat.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Gorduras Totais (Kcal)", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Light", 0, 18))); // NOI18N
        jPanel2.add(txtFat, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 180, -1));

        txtPositionAdd.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        txtPositionAdd.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Posição", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Light", 0, 18))); // NOI18N
        jPanel2.add(txtPositionAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 260, -1));

        btnSearch.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javalinkedlist/lupa.png"))); // NOI18N
        btnSearch.setMinimumSize(new java.awt.Dimension(5, 5));
        btnSearch.setPreferredSize(new java.awt.Dimension(5, 5));
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        jPanel2.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 510, 90, 90));

        btnSearchContains.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        btnSearchContains.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javalinkedlist/lupa2.png"))); // NOI18N
        btnSearchContains.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchContainsActionPerformed(evt);
            }
        });
        jPanel2.add(btnSearchContains, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 510, 90, 90));

        btnAdd.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        btnAdd.setText("Adicionar Alimento");
        btnAdd.setActionCommand("Adicionar Alimento");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel2.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 520, 200, 70));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javalinkedlist/seguranca-alimentar.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, 280, 270));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 630));

        jPanel3.setBackground(new java.awt.Color(102, 153, 0));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Controle dos Alimentos", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI Light", 1, 24))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        listFood.setEditable(false);
        listFood.setColumns(20);
        listFood.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        listFood.setRows(5);
        listFood.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lista de Alimentos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Light", 0, 24))); // NOI18N
        jScrollPane1.setViewportView(listFood);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 138, 487, 480));

        btnResolver.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        btnResolver.setText("Retirar Alimento");
        btnResolver.setActionCommand("");
        btnResolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResolverActionPerformed(evt);
            }
        });
        jPanel3.add(btnResolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 170, 70));

        txtPosicaoRemove.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        txtPosicaoRemove.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Posição", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Light", 0, 18))); // NOI18N
        jPanel3.add(txtPosicaoRemove, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 228, -1));

        btnOrdNutrition.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        btnOrdNutrition.setText("Ordenar por taxa de nutrição");
        btnOrdNutrition.setActionCommand("Ordenar por nutricao");
        btnOrdNutrition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdNutritionActionPerformed(evt);
            }
        });
        jPanel3.add(btnOrdNutrition, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 550, 270, 60));

        btnOrdEnergeticValue.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        btnOrdEnergeticValue.setText("Ordenar por saudável");
        btnOrdEnergeticValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdEnergeticValueActionPerformed(evt);
            }
        });
        jPanel3.add(btnOrdEnergeticValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 470, 210, 60));

        btnOrdName.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        btnOrdName.setLabel("Ordenar por nome");
        btnOrdName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdNameActionPerformed(evt);
            }
        });
        jPanel3.add(btnOrdName, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 390, 210, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javalinkedlist/doacao-de-alimentos.png"))); // NOI18N
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 80, 280, 270));

        lblProx.setFont(new java.awt.Font("Segoe Script", 0, 24)); // NOI18N
        lblProx.setForeground(new java.awt.Color(255, 255, 255));
        lblProx.setText("Alimento:");
        jPanel3.add(lblProx, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 30, 330, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 0, 830, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        int s=0;
        boolean found = false;
        for(Food a:list)
        {
            if(a.getName().contains(txtName.getText()))
            {
                JOptionPane.showMessageDialog(null, "Encontrado posicao "+s);
                found = true;
            }
            s++;
        }
        if(!found)
        {
            JOptionPane.showMessageDialog(null, "Não encontrado ");
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnSearchContainsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchContainsActionPerformed
        Food f = new Food();
        f.setName(txtName.getText());
        int p = list.indexOf(f);
        if(list.contains(f))
        {
            JOptionPane.showMessageDialog(null, "Encontrado posicao "+p);
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Não encontrado "+p);
        }
    }//GEN-LAST:event_btnSearchContainsActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        Food f = new Food();
        f.setName(txtName.getText());
        f.setEnergeticValue(Integer.parseInt(txtEnergeticValue.getText()));
        f.setNutrition(Integer.parseInt(txtNutrition.getText()));
        f.setFat(Integer.parseInt(txtFat.getText()));
        if(txtPositionAdd.getText().equals(""))
        {
            list.add(f);
        }
        else
        {
            list.add(Integer.parseInt(txtPositionAdd.getText()),f);
        }
        showList();
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnResolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResolverActionPerformed
        Food f;
        if(!list.isEmpty())
        {
            if(txtPosicaoRemove.getText().equals(""))
            {
                f = list.remove();
            }
            else
            {
                f = list.remove(Integer.parseInt(txtPosicaoRemove.getText()) );
            }
            lblProx.setText(f.getName());
            showList();
        }

    }//GEN-LAST:event_btnResolverActionPerformed

    private void btnOrdNutritionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdNutritionActionPerformed
        list.sort(compareNutrition);
        showList();
    }//GEN-LAST:event_btnOrdNutritionActionPerformed

    private void btnOrdEnergeticValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdEnergeticValueActionPerformed
        list.sort(compareEnergeticValue);
        showList();
    }//GEN-LAST:event_btnOrdEnergeticValueActionPerformed

    private void btnOrdNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdNameActionPerformed
        Collections.sort(list);
        showList();
    }//GEN-LAST:event_btnOrdNameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormSystem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnOrdEnergeticValue;
    private javax.swing.JButton btnOrdName;
    private javax.swing.JButton btnOrdNutrition;
    private javax.swing.JButton btnResolver;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSearchContains;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblProx;
    private javax.swing.JTextArea listFood;
    private javax.swing.JTextField txtEnergeticValue;
    private javax.swing.JTextField txtFat;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtNutrition;
    private javax.swing.JTextField txtPosicaoRemove;
    private javax.swing.JTextField txtPositionAdd;
    // End of variables declaration//GEN-END:variables
}
